- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: copy the hcl file
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true
