- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed



- name: start vault
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true
